#!/bin/bash

echo "Installing Vim from source..."

# Install Vim in the common subdirectory of
# the user's home directory
BASE_DIR=$HOME
export SRC_DIR=$BASE_DIR/common/src
export INSTALL_DIR=$BASE_DIR/common/install
mkdir -p $INSTALL_DIR
mkdir -p $SRC_DIR

if [[ -d $SRC_DIR/vim ]]
then
    rm -rf $SRC_DIR/vim
    rm -rf $INSTALL_DIR/vim
fi

cd $SRC_DIR
git clone https://github.com/vim/vim.git vim
cd $SRC_DIR/vim/src
make distclean
make -j10
make install
