#!/bin/bash                                                                                                                                         

if [[ -z $1 ]]
then
    echo "Please specify the desired version, e.g. 2.40.1"
    exit 1
fi

load-modules

# Install the specified version of Git
# in the common subdirectory of the user's home directory
BASE_DIR=$HOME
export SRC_DIR=$BASE_DIR/common/src
export INSTALL_DIR=$BASE_DIR/common/install
mkdir -p $INSTALL_DIR
mkdir -p $SRC_DIR

GIT_VER_NO=$1
GIT_VERSION=git-$GIT_VER_NO
cd $SRC_DIR
wget https://mirrors.edge.kernel.org/pub/software/scm/git/$GIT_VERSION.tar.gz
tar xvf $GIT_VERSION.tar.gz
export BUILD_DIR=$SRC_DIR/$GIT_VERSION
mkdir -p $BUILD_DIR
cd $BUILD_DIR
make configure
./configure --prefix=$INSTALL_DIR
make all
make install
